### ISSUE TITLE
Address should deduplicate wherever possible

### ISSUE THREAD

**Issue by willwagner602** [TW1LL/w3#13]
People should be able to make changes to their address, duplicate addresses shouldn't create a new address, and address changes should never modify an existing address (because it might be attached to a finalized order and we need the record historically)

**Comment by tfitz237** [comment]
should this be done by creating a table for customer addresses? so they can save/store/edit their addresses, aka "work", "home" ? and then instead of the final order holding the address it's just a reference?

**Comment by willwagner602** [comment]
Yeah there's actually a whole address model now, and I've got deduplication working.

I was thinking about adding a list of existing addresses for people to manage in account as well as the shipping address page, but honestly seems like overkill.  If Andrew ends up with lots and lots of customers who ship to multiple addresses we can always do some more work on it.

**Comment by tfitz237** [comment]
Overkill but easy to implement 😄

**Comment by willwagner602** [comment]
Aight I'll save it for hack time
