### ISSUE TITLE
Custom admin

### ISSUE THREAD

**Issue by willwagner602** [TW1LL/w3#19]
Admin needs to be able to see all relevant order information
Admin needs to be able to mark orders as "shipped"
Admin interface should have clear listings for open orders, history

**Comment by willwagner602** [comment]
Finished order pages

Need to do product pages

**Comment by tfitz237** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [asdf](https://trello.com/c/Cr0Rk7ZB/1-asdf)
